exports.names = [
  "Liam",
  "Noah",
  "William",
  "James",
  "Logan",
  "Benjamin",
  "Mason",
  "Elijah",
  "Oliver",
  "Jacob",
  "Lucas",
  "Michael",
  "Alexander",
  "Joseph",
  "Jackson",
  "Samuel",
  "Sebastian",
  "David",
  "Carter",
  "Wyatt",
  "Eric",
];
exports.focus = [
  "Aerial",
  "Corrective Exercise",
  "Bootcamp",
  "Boxing / kickboxing",
  "Circuit training",
  "Crossfit",
  "Cycling",
  "Dance",
  "Strength and Conditioning",
  "Gymnastics",
  "Interval training",
  "Martial arts",
  "Outdoor",
  "BodyBuilding",
  "Pilates",
  "Youth Exercise",
  "Rock climbing",
  "Sports",
  "Tai chi",
  "Nutrition",
  "Seniors Exercise",
  "Weight training",
  "Yoga",
];
exports.address = [
  {
    city: "Surrey",
    province: "BC",
    country: "Canada",
    fullAddress: "13450 104 Ave, Surrey, BC V3T 1V8",
  },
  {
    city: "Toronto",
    province: "ON",
    country: "Canada",
    fullAddress: "100 Queen St W, Toronto, ON M5H 2N2",
  },
  {
    city: "New York",
    province: "NY",
    country: "United States",
    fullAddress: "City Hall Park, New York, NY 10007, United States",
  },
];

exports.organization = [
  "ISSA (International Sports Sciences Association)",
  "NASM (National Academy of Sports Medicine)",
  "FM (Fitness Mentors)",
  "ACE (American Council on Exercise)",
  "NSCA (National Strength and Conditioning Association)",
  "ACSM (American College of Sports Medicine)",
  "NESTA (National Exercise & Sports Trainers Association)",
  "NCCPT (National Council for Certified Personal Trainers)",
  "NCSF (National Council on Strength & Fitness)",
  "AFAA (Athletics and Fitness Association of America)",
  "NFPT (National Federation of Professional Trainers)",
];
