export const _focus = [
  'Aerial',
  'Corrective Exercise',
  'Bootcamp',
  'Boxing / kickboxing',
  'Circuit training',
  'Crossfit',
  'Cycling',
  'Dance',
  'Strength and Conditioning',
  'Gymnastics',
  'Interval training',
  'Martial arts',
  'Outdoor',
  'BodyBuilding',
  'Pilates',
  'Youth Exercise',
  'Rock climbing',
  'Sports',
  'Tai chi',
  'Nutrition',
  'Seniors Exercise',
  'Weight training',
  'Yoga',
];
